### ISSUE TITLE
Unable to use "gulp serve"

### ISSUE THREAD

**Issue by gregllong** [labrad/scalabrad-web#178]
Hi, 

I tried to launch the scalabrad-web server on a Windows 7 machine following the instructions in README.md. I have successfully installed global and project-level dependencies using

``` bash
$ npm install -g gulp typescript jspm bower
$ npm install
$ jspm install
$ bower install
```

But when I tried to run the gulp build, I receive the following log:

``` bash
$ gulp serve
[11:11:41] Using gulpfile ~\code\scalabrad_web\client-js\gulpfile.js
[11:11:41] Starting 'compile-ts'...
error TS5023: Unknown compiler option 'experimentalAsyncFunctions'.
[11:11:41] Starting 'insert-dev-config'...
[11:11:41] Starting 'styles'...
[11:11:42] Starting 'elements'...
[11:11:42] Starting 'images'...
[11:11:42] Finished 'elements' after 483 ms
[11:11:42] insert-dev-config all files 2.09 kB
[11:11:42] Finished 'insert-dev-config' after 1.01 s
[11:11:43] styles all files 397 B
[11:11:43] Finished 'styles' after 1.11 s
[11:11:43] images all files 25.3 kB
[11:11:43] Finished 'images' after 795 ms
[11:11:45] Finished 'compile-ts' after 3.36 s
[11:11:45] Starting 'bundle'...

'node_modules' is not recognized as an internal or external command,
operable program or batch file.

[11:11:45] 'bundle' errored after 13 ms
[11:11:45] Error: Command failed: C:\Windows\system32\cmd.exe /s /c "node_modules/.bin/jspm bundle-sfx app/scripts/app .tmp/scripts/bundle.js --skip-source-maps"
'node_modules' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:477:12)
```

I have minimal knowledge on programming with scala, and any help is greatly appreciated.

Thank you!

**Comment by jwenner** [comment]
@gregllong, unless you are intending to do development work on this, it is best to use the version from bintray on Windows computers. There is a known compatibility issue (#48) for running the development version (i.e., the non-bintray version) on Windows. That being said, the solution in #48 might be of help.

**Comment by joshm-3b6b58** [comment]
@gregllong This error is for the client, gulp is what serves the client web-page and has nothing to do with scala. It seems like jspm isn't working. None of us have tried node on windows, I don't know if it works... 

I suggest using the bintray if you just want to use this interface and not develop for it.

**Comment by gregllong** [comment]
Thank you very much to @jwenner and @joshmutus . Now I can run scalabrad-web perfectly.

**Comment by maffoo** [comment]
closing, because it seems to be resolved for @gregllong
