### ISSUE TITLE
PID file problem

### ISSUE THREAD

**Issue by ejeffrey** [labrad/scalabrad-web#58]
The web server tries to save its PID in scalabrad-web-server/RUNNING_PID.  If it can't write to that file, it fails:

```
Oops, cannot start the server.
java.io.FileNotFoundException: /usr/local/scalabrad-web-server-1.0-SNAPSHOT/RUNNING_PID (Permission denied)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(FileOutputStream.java:270)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
    at play.core.server.ProdServerStart$.createPidFile(ProdServerStart.scala:131)
    at play.core.server.ProdServerStart$.start(ProdServerStart.scala:45)
    at play.core.server.ProdServerStart$.main(ProdServerStart.scala:27)
    at play.core.server.ProdServerStart.main(ProdServerStart.scala)
```

1) Does it really need a PID file?  That is not standard procedure on windows, and on linux it is often handled by the 'start-stop-daemon' program
2) If this is being used as a lock file, that doesn't seem necessary.  Starting a second server on the same port will fail
3) If it is needed, the location should be configurable so that it can go in /var/run

**Comment by maffoo** [comment]
You can change the path of the pid file: https://www.playframework.com/documentation/2.4.x/ProductionConfiguration#Changing-the-path-of-RUNNING_PID

I would like to move away from play because we're not really using it for much (all the web server needs to do is serve some static files and handle web sockets), but it will be a bit of work to change that.

**Comment by DanielSank** [comment]
+1 for this being annoying.

**Comment by adamcw** [comment]
@maffoo Since #64 was closed, does that mean this can be closed too?

**Comment by maffoo** [comment]
Yup, this is fixed.
