### ISSUE TITLE
Compilation error in gulp serve

### ISSUE THREAD

**Issue by DanielSank** [labrad/scalabrad-web#63]
Tried installing on my laptop. Node version `v0.12.6`.
Note the warning doesn't seem to have anything to do with the error.

```
danielsank@snail:~/src/scalabrad-web/client-js$ bower install
? May bower anonymously report usage statistics to improve the tool over time? No
bower not-cached    git://github.com/nippur72/PolymerTS.git#~0.1.13
bower resolve       git://github.com/nippur72/PolymerTS.git#~0.1.13
bower not-cached    git://github.com/PolymerElements/paper-tooltip.git#~1.1.0
bower resolve       git://github.com/PolymerElements/paper-tooltip.git#~1.1.0
bower download      https://github.com/PolymerElements/paper-tooltip/archive/v1.1.0.tar.gz
bower download      https://github.com/nippur72/PolymerTS/archive/0.1.20.tar.gz
bower extract       paper-tooltip#~1.1.0 archive.tar.gz
bower resolved      git://github.com/PolymerElements/paper-tooltip.git#1.1.0
bower not-cached    git://github.com/Polymer/polymer.git#^1.1.0
bower resolve       git://github.com/Polymer/polymer.git#^1.1.0
bower extract       polymer-ts#~0.1.13 archive.tar.gz
bower download      https://github.com/Polymer/polymer/archive/v1.1.3.tar.gz
bower resolved      git://github.com/nippur72/PolymerTS.git#0.1.20
bower not-cached    git://github.com/Polymer/polymer.git#>=1.0.8
bower resolve       git://github.com/Polymer/polymer.git#>=1.0.8
bower not-cached    git://github.com/Polymer/webcomponentsjs.git#>=0.7.10
bower resolve       git://github.com/Polymer/webcomponentsjs.git#>=0.7.10
bower download      https://github.com/Polymer/polymer/archive/v1.1.3.tar.gz
bower download      https://github.com/Polymer/webcomponentsjs/archive/v0.7.12.tar.gz
bower extract       polymer#^1.1.0 archive.tar.gz
bower resolved      git://github.com/Polymer/polymer.git#1.1.3
bower cached        git://github.com/Polymer/polymer.git#1.0.5
bower validate      1.0.5 against git://github.com/Polymer/polymer.git#~1.0.0
bower new           version for git://github.com/Polymer/polymer.git#~1.0.0
bower resolve       git://github.com/Polymer/polymer.git#~1.0.0
bower download      https://github.com/Polymer/polymer/archive/v1.0.9.tar.gz
bower extract       polymer#>=1.0.8 archive.tar.gz
bower resolved      git://github.com/Polymer/polymer.git#1.1.3
bower extract       polymer#~1.0.0 archive.tar.gz
bower resolved      git://github.com/Polymer/polymer.git#1.0.9
bower extract       webcomponentsjs#>=0.7.10 archive.tar.gz
bower resolved      git://github.com/Polymer/webcomponentsjs.git#0.7.12

Please note that,
    iron-a11y-announcer#1.0.1, iron-a11y-keys#1.0.2, iron-a11y-keys-behavior#1.0.5, iron-ajax#1.0.2, iron-autogrow-textarea#1.0.2, iron-behaviors#1.0.4, iron-collapse#1.0.2, iron-component-page#1.0.5, iron-doc-viewer#1.0.3, iron-fit-behavior#1.0.3, iron-flex-layout#1.0.2, iron-form#1.0.4, iron-form-element-behavior#1.0.1, iron-icon#1.0.2, iron-icons#1.0.3, iron-iconset#1.0.2, iron-iconset-svg#1.0.4, iron-image#1.0.2, iron-input#1.0.3, iron-jsonp-library#1.0.2, iron-localstorage#1.0.3, iron-media-query#1.0.2, iron-menu-behavior#1.0.1, iron-meta#1.0.3, iron-overlay-behavior#1.0.4, iron-pages#1.0.2, iron-range-behavior#1.0.2, iron-resizable-behavior#1.0.2, iron-selector#1.0.2, iron-signals#1.0.2, iron-test-helpers#1.0.1, iron-validatable-behavior#1.0.2, iron-validator-behavior#1.0.1, marked-element#1.0.2, neon-animation#1.0.5, paper-behaviors#1.0.2, paper-button#1.0.2, paper-checkbox#1.0.3, paper-dialog#1.0.0, paper-dialog-behavior#1.0.4, paper-dialog-scrollable#1.0.1, paper-drawer-panel#1.0.2, paper-fab#1.0.2, paper-header-panel#1.0.2, paper-icon-button#1.0.2, paper-input#1.0.5, paper-item#1.0.1, paper-material#1.0.0, paper-menu#1.0.0, paper-progress#1.0.0, paper-radio-button#1.0.3, paper-radio-group#1.0.3, paper-ripple#1.0.1, paper-scroll-header-panel#1.0.4, paper-slider#1.0.3, paper-spinner#1.0.1, paper-styles#1.0.7, paper-tabs#1.0.0, paper-toast#1.0.0, paper-toggle-button#1.0.3, paper-toolbar#1.0.2, platinum-sw#1.0.2, prism-element#1.0.2, promise-polyfill#1.0.0, test-fixture#1.0.0 depends on polymer#^1.0.0 which resolved to polymer#1.0.5
    platinum-push-messaging#1.0.0 depends on polymer#~1.0.0 which resolved to polymer#1.0.9
    paper-tooltip#1.1.0 depends on polymer#^1.1.0 which resolved to polymer#1.1.3
    polymer-ts#0.1.20 depends on polymer#>=1.0.8 which resolved to polymer#1.1.3
Resort to using polymer#^1.0.0 which resolved to polymer#1.0.5
Code incompatibilities may occur.

bower extra-resolution      Unnecessary resolution: webcomponentsjs#^0.7.2
bower extra-resolution      Unnecessary resolution: iron-ajax#^1.0.0
bower extra-resolution      Unnecessary resolution: promise-polyfill#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-autogrow-textarea#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-validatable-behavior#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-behaviors#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-a11y-keys-behavior#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-collapse#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-component-page#^1.0.0
bower extra-resolution      Unnecessary resolution: paper-toolbar#^1.0.0
bower extra-resolution      Unnecessary resolution: paper-header-panel#^1.0.0
bower extra-resolution      Unnecessary resolution: marked-element#^1.0.0
bower extra-resolution      Unnecessary resolution: prism-element#^1.0.2
bower extra-resolution      Unnecessary resolution: iron-fit-behavior#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-flex-layout#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-icon#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-icons#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-iconset#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-iconset-svg#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-image#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-input#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-jsonp-library#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-localstorage#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-media-query#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-meta#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-overlay-behavior#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-pages#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-resizable-behavior#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-selector#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-signals#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-test-helpers#^1.0.0
bower extra-resolution      Unnecessary resolution: paper-behaviors#^1.0.0
bower extra-resolution      Unnecessary resolution: paper-button#^1.0.0
bower extra-resolution      Unnecessary resolution: paper-checkbox#^1.0.0
bower extra-resolution      Unnecessary resolution: paper-dialog-scrollable#^1.0.0
bower extra-resolution      Unnecessary resolution: paper-drawer-panel#^1.0.0
bower extra-resolution      Unnecessary resolution: paper-fab#^1.0.0
bower extra-resolution      Unnecessary resolution: paper-icon-button#^1.0.0
bower extra-resolution      Unnecessary resolution: paper-input#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-form-element-behavior#^1.0.0
bower extra-resolution      Unnecessary resolution: paper-item#^1.0.0
bower extra-resolution      Unnecessary resolution: paper-material#^1.0.0
bower extra-resolution      Unnecessary resolution: paper-menu#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-menu-behavior#^1.0.0
bower extra-resolution      Unnecessary resolution: paper-radio-button#^1.0.0
bower extra-resolution      Unnecessary resolution: paper-radio-group#^1.0.0
bower extra-resolution      Unnecessary resolution: paper-ripple#^1.0.0
bower extra-resolution      Unnecessary resolution: paper-spinner#^1.0.0
bower extra-resolution      Unnecessary resolution: paper-tabs#^1.0.0
bower extra-resolution      Unnecessary resolution: paper-toast#^1.0.0
bower extra-resolution      Unnecessary resolution: iron-a11y-announcer#^1.0.0
bower extra-resolution      Unnecessary resolution: paper-toggle-button#^1.0.0
bower extra-resolution      Unnecessary resolution: platinum-sw#~1.0.0
bower install               webcomponentsjs#0.7.12
bower install               paper-tooltip#1.1.0
bower install               polymer-ts#0.1.20

webcomponentsjs#0.7.12 bower_components/webcomponentsjs

paper-tooltip#1.1.0 bower_components/paper-tooltip
├── neon-animation#1.0.5
├── paper-styles#1.0.7
└── polymer#1.0.5

polymer-ts#0.1.20 bower_components/polymer-ts
├── polymer#1.0.5
└── webcomponentsjs#0.7.12
danielsank@snail:~/src/scalabrad-web/client-js$ gulp serve
[21:53:51] Using gulpfile ~/src/scalabrad-web/client-js/gulpfile.js
[21:53:51] Starting 'compile-ts'...
[21:53:51] Starting 'insert-dev-config'...
[21:53:51] Starting 'styles'...
[21:53:51] Starting 'elements'...
[21:53:51] Starting 'images'...
[21:53:52] Finished 'elements' after 564 ms
[21:53:52] 'insert-dev-config' all files 3.92 kB
[21:53:52] Finished 'insert-dev-config' after 1.11 s
[21:53:52] 'styles' all files 223 B
[21:53:52] Finished 'styles' after 1.14 s
/home/danielsank/src/scalabrad-web/client-js/node_modules/typescript/lib/typescript.js:35284
                if (host.fileExists(candidate)) {
                         ^
TypeError: undefined is not a function
    at /home/danielsank/src/scalabrad-web/client-js/node_modules/typescript/lib/typescript.js:35284:26
    at Object.forEach (/home/danielsank/src/scalabrad-web/client-js/node_modules/typescript/lib/typescript.js:880:30)
    at classicNameResolver (/home/danielsank/src/scalabrad-web/client-js/node_modules/typescript/lib/typescript.js:35277:39)
    at resolveModuleName (/home/danielsank/src/scalabrad-web/client-js/node_modules/typescript/lib/typescript.js:35171:42)
    at /home/danielsank/src/scalabrad-web/client-js/node_modules/typescript/lib/typescript.js:35430:115
    at Object.map (/home/danielsank/src/scalabrad-web/client-js/node_modules/typescript/lib/typescript.js:945:29)
    at resolveModuleNamesWorker (/home/danielsank/src/scalabrad-web/client-js/node_modules/typescript/lib/typescript.js:35430:67)
    at processImportedModules (/home/danielsank/src/scalabrad-web/client-js/node_modules/typescript/lib/typescript.js:35862:35)
    at findSourceFile (/home/danielsank/src/scalabrad-web/client-js/node_modules/typescript/lib/typescript.js:35824:21)
    at processSourceFile (/home/danielsank/src/scalabrad-web/client-js/node_modules/typescript/lib/typescript.js:35760:27)
    at processRootFile (/home/danielsank/src/scalabrad-web/client-js/node_modules/typescript/lib/typescript.js:35699:13)
    at /home/danielsank/src/scalabrad-web/client-js/node_modules/typescript/lib/typescript.js:35445:60
    at Object.forEach (/home/danielsank/src/scalabrad-web/client-js/node_modules/typescript/lib/typescript.js:880:30)
    at Object.createProgram (/home/danielsank/src/scalabrad-web/client-js/node_modules/typescript/lib/typescript.js:35445:16)
    at ProjectCompiler.inputDone (/home/danielsank/src/scalabrad-web/client-js/node_modules/gulp-typescript/release/compiler.js:63:48)
    at CompileStream.end (/home/danielsank/src/scalabrad-web/client-js/node_modules/gulp-typescript/release/main.js:53:31)
```

**Comment by maffoo** [comment]
It looks like you picked up typescript 1.6 when you did `npm install`. Feel free to try to debug the typescript compilation if you want, but for now I would suggest just downgrading to typescript 1.5.x.

To check what version you have, you can use `npm list`. On my machine:

```
$ npm list -g | grep typescript
├── typescript@1.5.3
$ npm list | grep typescript
├─┬ gulp-typescript@2.8.0
├── typescript@1.5.3
├── typescript-loader@1.1.3 extraneous
├── typescript-register@1.1.0 extraneous
```

To install a specific version, you can do:

```
$ npm install -g typescript@1.5.3
$ npm install typescript@1.5.3
```

**Comment by maffoo** [comment]
@DanielSank, please try downgrading typescript. If that works, we can then either modify the npm packages list to restrict the typescript version appropriately, or else get things working with typescript 1.6.
